<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dist_intranet"
 *
 * Auto generated by Extension Builder 2018-11-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Intranet-Distribution',
    'description' => 'Distribution for a Corporate intranet.',
    'category' => 'distribution',
    'author' => 'Mike Tölle',
    'author_email' => 'development@typo3graf.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
